// src/compose/hosts.ts without the writes: the two files `generate` leaves in files/, as text.

import { listInstances, type PlaygroundConfig } from './config';

/** Every name any instance answers to, once, sorted. */
export function collectHostnames(config: PlaygroundConfig): string[] {
  return [...new Set(listInstances(config).flatMap((instance) => instance.hostnames))].sort();
}

/** The names nothing resolves on its own: *.localhost already points home, *.fediverse does not. */
export function collectFediverseHostnames(config: PlaygroundConfig): string[] {
  return collectHostnames(config).filter((hostname) => hostname.endsWith('.fediverse'));
}

/** files/hosts.snippet, the block `apply-hosts` merges into /etc/hosts. */
export function hostsSnippet(config: PlaygroundConfig): string {
  return `# Generated by fediverse-playground \u2014 do not edit manually.
# Merge with: fediverse-playground apply-hosts
127.0.0.1 ${collectHostnames(config).join(' ')}
`;
}

/** files/hosts.nix, the attribute set nix/hosts-module.nix hands to networking.hosts. */
export function hostsNix(config: PlaygroundConfig): string {
  const lines = collectFediverseHostnames(config).map((hostname) => `    "${hostname}"`).join('\n');
  return `# Generated by fediverse-playground \u2014 do not edit manually.
# Optional: import nix/hosts-module.nix into NixOS configuration.nix.
{
  "127.0.0.1" = [
${lines}
  ];
}
`;
}

/** The recipe's certificate: one openssl call whose SAN lists every name the instance answers to. */
export function subjectAltName(hostnames: readonly string[]): string {
  return `subjectAltName=${hostnames.map((hostname) => `DNS:${hostname}`).join(',')}`;
}
