// Just enough YAML to print a compose file: block maps and sequences of strings, numbers and
// booleans. The tool itself uses the `yaml` package; shipping that to a browser to print one
// shape of document is not worth its weight. Long plain strings are left on one line where
// `yaml` would fold them at 80 columns; both parse to the same document.
//
// The emitter knows what each piece of a line is as it writes it, so it hands back tokens, and
// it needs no tokeniser in the browser. `composeYaml` joins them into the text the tool writes;
// `composeHtml` wraps each in a span with the class the site's highlighter (src/highlight.ts)
// gives the same token, so the file takes the same colours as the other sheets' code.

const HEADER = '# This file was generated by Fediverse Playground (GPL3+)';

// Each kind is the one the site's highlighter gives the same token as its YAML grammar reads
// it: a key is a tag, and a plain scalar a string like a quoted one.
type Kind = 'tag' | 'string' | 'number' | 'punctuation' | 'comment';
type Token = { kind: Kind | null; text: string };
type Line = Token[];

// What a plain scalar may not look like: something the core schema reads as another type,
// or something that starts with an indicator or holds a key or comment separator.
const LOOKS_TYPED = /^(?:[-+]?(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][-+]?\d+)?|[-+]?\.(?:inf|Inf|INF)|\.(?:nan|NaN|NAN)|0x[0-9a-fA-F]+|0o[0-7]+|true|True|TRUE|false|False|FALSE|null|Null|NULL|~)$/;
const INDICATOR_FIRST = /^[-?:,[\]{}#&*!|>'"%@`\s]/;

function scalar(value: unknown): Token {
  if (typeof value === 'number' || typeof value === 'boolean') return { kind: 'number', text: String(value) };
  const text = String(value);
  const plain = text !== ''
    && !LOOKS_TYPED.test(text)
    && !INDICATOR_FIRST.test(text)
    && !/: |:$| #|\s$|\n/.test(text);
  return { kind: 'string', text: plain ? text : JSON.stringify(text) };
}

const isMap = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const pad = (indent: string): Token => ({ kind: null, text: indent });

function block(value: unknown, indent: string): Line[] {
  if (Array.isArray(value)) {
    return value.flatMap((item): Line[] => {
      if (isMap(item) || Array.isArray(item)) {
        const [first, ...rest] = block(item, `${indent}  `);
        return [[pad(indent), { kind: 'punctuation', text: '- ' }, ...first.slice(1)], ...rest];
      }
      return [[pad(indent), { kind: 'punctuation', text: '- ' }, scalar(item)]];
    });
  }

  if (isMap(value)) {
    return Object.entries(value).flatMap(([key, item]): Line[] => {
      const head: Line = [pad(indent), { kind: 'tag', text: key }, { kind: 'punctuation', text: ':' }];
      if (isMap(item) && Object.keys(item).length === 0) return [[...head, { kind: 'punctuation', text: ' {}' }]];
      if (Array.isArray(item) && item.length === 0) return [[...head, { kind: 'punctuation', text: ' []' }]];
      if (isMap(item) || Array.isArray(item)) return [head, ...block(item, `${indent}  `)];
      return [[...head, { kind: null, text: ' ' }, scalar(item)]];
    });
  }

  return [[pad(indent), scalar(value)]];
}

const lines = (document: Record<string, unknown>): Line[] => [[{ kind: 'comment', text: HEADER }], ...block(document, '')];

/** builder.ts's writeComposeFile, without the write: the header line, then the document. */
export function composeYaml(document: Record<string, unknown>): string {
  return `${lines(document).map((line) => line.map((token) => token.text).join('')).join('\n')}\n`;
}

const escape = (text: string) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** The same text as markup, one span per token that has a colour. */
export function composeHtml(document: Record<string, unknown>): string {
  return lines(document)
    .map((line) => line
      .map(({ kind, text }) => (kind ? `<span class="tok-${kind}">${escape(text)}</span>` : escape(text)))
      .join(''))
    .join('\n');
}
