// Just enough YAML to print a compose file: block maps and sequences of strings, numbers and
// booleans. The tool itself uses the `yaml` package; shipping that to a browser to print one
// shape of document is not worth its weight. Long plain strings are left on one line where
// `yaml` would fold them at 80 columns; both parse to the same document.

const HEADER = '# This file was generated by Fediverse Playground (GPL3+)\n';

// What a plain scalar may not look like: something the core schema reads as another type,
// or something that starts with an indicator or holds a key or comment separator.
const LOOKS_TYPED = /^(?:[-+]?(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][-+]?\d+)?|[-+]?\.(?:inf|Inf|INF)|\.(?:nan|NaN|NAN)|0x[0-9a-fA-F]+|0o[0-7]+|true|True|TRUE|false|False|FALSE|null|Null|NULL|~)$/;
const INDICATOR_FIRST = /^[-?:,[\]{}#&*!|>'"%@`\s]/;

function scalar(value: unknown): string {
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  const text = String(value);
  const plain = text !== ''
    && !LOOKS_TYPED.test(text)
    && !INDICATOR_FIRST.test(text)
    && !/: |:$| #|\s$|\n/.test(text);
  return plain ? text : JSON.stringify(text);
}

const isMap = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

function block(value: unknown, indent: string): string[] {
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (isMap(item) || Array.isArray(item)) {
        const [first, ...rest] = block(item, `${indent}  `);
        return [`${indent}- ${first.trimStart()}`, ...rest];
      }
      return [`${indent}- ${scalar(item)}`];
    });
  }

  if (isMap(value)) {
    return Object.entries(value).flatMap(([key, item]) => {
      if (isMap(item) && Object.keys(item).length === 0) return [`${indent}${key}: {}`];
      if (Array.isArray(item) && item.length === 0) return [`${indent}${key}: []`];
      if (isMap(item)) return [`${indent}${key}:`, ...block(item, `${indent}  `)];
      if (Array.isArray(item)) return [`${indent}${key}:`, ...block(item, `${indent}  `)];
      return [`${indent}${key}: ${scalar(item)}`];
    });
  }

  return [`${indent}${scalar(value)}`];
}

/** builder.ts's writeComposeFile, without the write: the header line, then the document. */
export function composeYaml(document: Record<string, unknown>): string {
  return `${HEADER}${block(document, '').join('\n')}\n`;
}
