import type { Locator, Page } from '@playwright/test';

import { frontPage, frontPageIndex, frontPageName } from './support/paperStack';
import { expect, pageWait, test } from './support/timeScale';

const PAGES = ['Fediverse Playground', 'Mirrors & Worktrees', 'One-shot Installers', 'Hostnames → /etc/hosts'];

test.beforeEach(async ({ page }) => {
  await page.goto('/');
});

function playgroundStack(page: Page) {
  // By title, not by position: the demos run gains stacks over time.
  return page.locator('article.technical-drawing-stack').filter({
    has: page.locator('h2.typewriter', { hasText: 'Fediverse Playground' }),
  });
}

async function mountedPlayground(page: Page) {
  const stack = playgroundStack(page);
  await stack.scrollIntoViewIfNeeded();
  const front = frontPage(stack, await frontPageIndex(stack));
  const host = front.locator('[data-fediverse-playground]');
  await expect(host).toHaveAttribute('data-mounted', 'true', { timeout: 15_000 });
  return host;
}

// The sheet holds a landscape and a portrait drawing and shows one; the other's nodes are hidden.
const node = (host: Locator, service: string) => host.locator(`.service-graph:visible .node[data-service="${service}"]`);

/** One page on with the arrow key: no hand on the paper, so the turn commits on the spot and
    does not hang on how quickly the wheel events come through. Waits until the named page is
    in front, rather than a fixed time the flip may or may not take under load. */
async function turnForwardTo(page: Page, stack: Locator, name: string, note: string) {
  await stack.focus();
  await page.keyboard.press('ArrowRight');
  await expect.poll(() => frontPageName(stack), { message: note, timeout: 10_000 }).toBe(name);
}

test('fediverse playground: the arrow key visits every page in order, then wraps', async ({ page }) => {
  const stack = playgroundStack(page);
  await stack.scrollIntoViewIfNeeded();

  expect(await stack.locator(':scope > div').count()).toBe(PAGES.length);
  await expect.poll(() => frontPageName(stack)).toBe(PAGES[0]);

  for (let i = 1; i < PAGES.length; i += 1) {
    await turnForwardTo(page, stack, PAGES[i], `page ${i} after ${i} turn(s)`);
  }

  await turnForwardTo(page, stack, PAGES[0], 'wrapped to the first page');
});

test.describe('with reduced motion', () => {
  // The walkthrough stays off, so every toggle starts from the config the page opens on.
  test.use({ reducedMotion: 'reduce' });

  test('main page: the toggles rebuild the graph, and shared services appear once', async ({ page }) => {
    const host = await mountedPlayground(page);
    const toggle = (name: string) => host.locator(`input[name="${name}"]`);

    // The opening state: the two v3 nodes up, the v2 node off.
    for (const service of ['web', 'db', 'redis', 'gnusocial-alice', 'gnusocial-alice-install', 'gnusocial-bob']) {
      await expect(node(host, service)).toHaveClass(/emitted/);
    }
    await expect(node(host, 'mariadb')).toHaveClass(/ghost/);
    await expect(host.locator('[data-status]')).toHaveText('7 services · 10 depends_on, all defined');

    // The v2 node brings mariadb with it; db is still drawn once.
    await toggle('gnusocial-v2').check();
    await expect(node(host, 'mariadb')).toHaveClass(/emitted/);
    await expect(node(host, 'gnusocial-v2-install')).toHaveClass(/emitted/);
    await expect(host.locator('.service-graph:visible .node[data-service="db"]')).toHaveCount(1);

    // With only v2 left, nothing asks for Postgres or Redis, and the builder does not emit them.
    await toggle('gnusocial-alice').uncheck();
    await toggle('gnusocial-bob').uncheck();
    await expect(node(host, 'db')).toHaveClass(/ghost/);
    await expect(node(host, 'redis')).toHaveClass(/ghost/);
    await expect(node(host, 'web')).toHaveClass(/emitted/);

    await toggle('gnusocial-v2').uncheck();
    await expect(node(host, 'web')).toHaveClass(/ghost/);
    await expect(host.locator('[data-status]')).toHaveText('No instances: services is empty');
  });

  test('main page: the YAML pane shows the file the builder writes', async ({ page }) => {
    const host = await mountedPlayground(page);
    const pane = host.locator('details.yaml');
    const code = pane.locator('[data-yaml]');

    await expect(code).toBeHidden();
    await pane.locator('summary').click();
    await expect(code).toBeVisible();
    await expect(code).toContainText('# This file was generated by Fediverse Playground (GPL3+)');
    await expect(code).not.toContainText('gnusocial-v2');

    await host.locator('input[name="gnusocial-v2"]').check();
    await expect(code).toContainText('gnusocial-v2-install:');
    // web waits on every app, and only on apps.
    await expect(code).toContainText('depends_on:\n      - gnusocial-alice\n      - gnusocial-bob\n      - gnusocial-v2\n');
  });
});

test.describe('walkthrough', () => {
  // The quiet spell before the walkthrough comes back is 6 s of page time.
  test.use({ walkthroughRate: 3 });

  async function playingPlayground(page: Page) {
    const host = await mountedPlayground(page);
    await expect(host).toHaveAttribute('data-autoplay', 'playing');
    const deck = host.locator('xpath=ancestor::section[1]').locator('[data-demo-transport]');
    return { host, deck };
  }

  test('it flips the toggles itself and reports to the deck', { tag: '@handover' }, async ({ page }) => {
    const { host, deck } = await playingPlayground(page);
    await expect(deck).toBeVisible();
    await expect(deck).toHaveAttribute('data-state', 'playing');
    await expect(deck.locator('[data-demo-caption]')).toHaveText('AUTO PLAYING');

    // Its first move switches v2 on, which brings MariaDB into the file.
    await expect(host.locator('input[name="gnusocial-v2"]')).toBeChecked({ timeout: 10_000 });
    await expect(node(host, 'mariadb')).toHaveClass(/emitted/);
    await expect(host.locator('.demo-cursor')).toBeVisible();

    // Then the v3 pair leaves, and nothing asks for Postgres any more.
    await expect(host.locator('input[name="gnusocial-alice"]')).not.toBeChecked({ timeout: 30_000 });
    await expect(host.locator('input[name="gnusocial-bob"]')).not.toBeChecked({ timeout: 10_000 });
    await expect(node(host, 'db')).toHaveClass(/ghost/);
  });

  test('moving over it takes over, and nothing flips after that', { tag: '@handover' }, async ({ page }) => {
    const { host, deck } = await playingPlayground(page);
    await expect(host.locator('input[name="gnusocial-v2"]')).toBeChecked({ timeout: 10_000 });

    await host.hover();
    await expect(host).toHaveAttribute('data-autoplay', 'user');
    await expect(deck).toHaveAttribute('data-state', 'user');
    await expect(host.locator('.demo-cursor')).toBeHidden();

    const checked = () => host.locator('input[type=checkbox]').evaluateAll((inputs) =>
      inputs.map((input) => (input as HTMLInputElement).checked));
    const settled = await checked();
    await pageWait(page, 3_000);
    expect(await checked()).toEqual(settled);

    // Left alone, it hands back.
    await page.mouse.move(0, 0);
    await expect(host).toHaveAttribute('data-autoplay', 'playing', { timeout: 10_000 });
  });

  test('the deck keys pause, play and reset it', { tag: '@handover' }, async ({ page }) => {
    const { host, deck } = await playingPlayground(page);
    const key = (name: string) => deck.locator(`[data-demo-key="${name}"]`);
    const alice = host.locator('input[name="gnusocial-alice"]');

    await key('pause').click();
    await expect(host).toHaveAttribute('data-autoplay', 'user');
    await expect(key('pause')).toHaveAttribute('aria-pressed', 'true');
    // Pause holds past the quiet spell that hands a hover back.
    await pageWait(page, 9_000);
    await expect(host).toHaveAttribute('data-autoplay', 'user');

    await key('play').click();
    await expect(host).toHaveAttribute('data-autoplay', 'playing');
    await expect(deck).toHaveAttribute('data-state', 'playing');

    // Reset puts the opening config back and starts over.
    await key('pause').click();
    await expect(host).toHaveAttribute('data-autoplay', 'user');
    await alice.uncheck();
    await expect(node(host, 'gnusocial-alice')).toHaveClass(/ghost/);
    await key('reset').click();
    await expect(host).toHaveAttribute('data-autoplay', 'playing');
    await expect(alice).toBeChecked();
    await expect(node(host, 'gnusocial-alice')).toHaveClass(/emitted/);
  });
});
