import { expect, test, type Locator, type Page } from '@playwright/test';

import { frontPage, frontPageIndex, frontPageName } from './support/paperStack';

const PAGES = ['Fediverse Playground', 'Mirrors & Worktrees', 'One-shot Installers', 'Hostnames → /etc/hosts'];

test.beforeEach(async ({ page }) => {
  await page.goto('/');
});

function playgroundStack(page: Page) {
  // By title, not by position: the demos run gains stacks over time.
  return page.locator('article.technical-drawing-stack').filter({
    has: page.locator('h2.typewriter', { hasText: 'Fediverse Playground' }),
  });
}

async function mountedPlayground(page: Page) {
  const stack = playgroundStack(page);
  await stack.scrollIntoViewIfNeeded();
  const front = frontPage(stack, await frontPageIndex(stack));
  const host = front.locator('[data-fediverse-playground]');
  await expect(host).toHaveAttribute('data-mounted', 'true', { timeout: 15_000 });
  return host;
}

// The sheet holds a landscape and a portrait drawing and shows one; the other's nodes are hidden.
const node = (host: Locator, service: string) => host.locator(`.service-graph:visible .node[data-service="${service}"]`);

/** One page on with the arrow key: no hand on the paper, so the turn commits on the spot and
    does not hang on how quickly the wheel events come through. */
async function turnForward(page: Page, stack: Locator) {
  await stack.focus();
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(2500);
}

test('fediverse playground: the arrow key visits every page in order, then wraps', async ({ page }) => {
  const stack = playgroundStack(page);
  await stack.scrollIntoViewIfNeeded();
  await page.waitForTimeout(500);

  expect(await stack.locator(':scope > div').count()).toBe(PAGES.length);
  expect(await frontPageName(stack)).toBe(PAGES[0]);

  for (let i = 1; i < PAGES.length; i += 1) {
    await turnForward(page, stack);
    expect(await frontPageName(stack), `page ${i} after ${i} turn(s)`).toBe(PAGES[i]);
  }

  await turnForward(page, stack);
  expect(await frontPageName(stack)).toBe(PAGES[0]);
});

test('main page: the toggles rebuild the graph, and shared services appear once', async ({ page }) => {
  const host = await mountedPlayground(page);
  const toggle = (name: string) => host.locator(`input[name="${name}"]`);

  // The opening state: the two v3 nodes up, the v2 node off.
  for (const service of ['web', 'db', 'redis', 'gnusocial-alice', 'gnusocial-alice-install', 'gnusocial-bob']) {
    await expect(node(host, service)).toHaveClass(/emitted/);
  }
  await expect(node(host, 'mariadb')).toHaveClass(/ghost/);
  await expect(host.locator('[data-status]')).toHaveText('7 services · 10 depends_on, all defined');

  // The v2 node brings mariadb with it; db is still drawn once.
  await toggle('gnusocial-v2').check();
  await expect(node(host, 'mariadb')).toHaveClass(/emitted/);
  await expect(node(host, 'gnusocial-v2-install')).toHaveClass(/emitted/);
  await expect(host.locator('.service-graph:visible .node[data-service="db"]')).toHaveCount(1);

  // With only v2 left, nothing asks for Postgres or Redis, and the builder does not emit them.
  await toggle('gnusocial-alice').uncheck();
  await toggle('gnusocial-bob').uncheck();
  await expect(node(host, 'db')).toHaveClass(/ghost/);
  await expect(node(host, 'redis')).toHaveClass(/ghost/);
  await expect(node(host, 'web')).toHaveClass(/emitted/);

  await toggle('gnusocial-v2').uncheck();
  await expect(node(host, 'web')).toHaveClass(/ghost/);
  await expect(host.locator('[data-status]')).toHaveText('No instances: services is empty');
});

test('main page: the YAML pane shows the file the builder writes', async ({ page }) => {
  const host = await mountedPlayground(page);
  const pane = host.locator('details.yaml');
  const code = pane.locator('[data-yaml]');

  await expect(code).toBeHidden();
  await pane.locator('summary').click();
  await expect(code).toBeVisible();
  await expect(code).toContainText('# This file was generated by Fediverse Playground (GPL3+)');
  await expect(code).not.toContainText('gnusocial-v2');

  await host.locator('input[name="gnusocial-v2"]').check();
  await expect(code).toContainText('gnusocial-v2-install:');
  // web waits on every app, and only on apps.
  await expect(code).toContainText('depends_on:\n      - gnusocial-alice\n      - gnusocial-bob\n      - gnusocial-v2\n');
});
